#!/usr/bin/env python3
"""Vendor Google Fonts woff2 for offline self-hosting + generate src/styles/fonts.css."""
import os, re, subprocess, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "public", "fonts")
os.makedirs(OUT, exist_ok=True)

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

CSS_URL = (
    "https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62.5..125,100..900"
    "&family=Inter:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500;700"
    "&display=swap"
)

css = subprocess.run(["curl", "-s", "-A", UA, CSS_URL],
                     capture_output=True, text=True, check=True).stdout

blocks = re.findall(r"@font-face\s*\{(.*?)\}", css, flags=re.S)
if not blocks:
    sys.exit("no @font-face blocks found")

clean_family = lambda s: re.sub(r"[^a-z0-9]", "", s.lower())

index = {}
rules = []
for n, block in enumerate(blocks):
    family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
    weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
    stretch = re.search(r"font-stretch:\s*([^;]+);", block)
    stretch = stretch.group(1).strip() if stretch else "normal"
    uni = re.search(r"unicode-range:\s*([^;]+);", block)
    uni = uni.group(1).strip() if uni else ""
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

    key = clean_family(family)
    if url not in index:
        idx = len(index)
        fname = f"{key}-{idx}.woff2"
        index[url] = fname
    else:
        fname = index[url]

    local = os.path.join(OUT, fname)
    if not os.path.exists(local):
        print(f"downloading {fname}  <-  {family} w{weight} {stretch}")
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req) as r, open(local, "wb") as f:
            f.write(r.read())

    uni_decl = f"    unicode-range: {uni};\n" if uni else ""
    rules.append(
        f"@font-face {{\n"
        f"    font-family: '{family}';\n"
        f"    font-style: {style};\n"
        f"    font-weight: {weight};\n"
        f"    font-stretch: {stretch};\n"
        f"{uni_decl}"
        f"    src: url('/fonts/{fname}') format('woff2');\n"
        f"    font-display: swap;\n"
        f"}}\n"
    )

css_dest = os.path.join(ROOT, "src", "styles", "fonts.css")
os.makedirs(os.path.dirname(css_dest), exist_ok=True)
with open(css_dest, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by scripts/fetch-fonts.py — self-hosted woff2 */\n\n")
    f.write("\n".join(rules))

print(f"wrote {css_dest} with {len(rules)} @font-face rules")
