/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixItRouteImport } from './routes/fix-it'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as KitRouteImport } from './routes/kit'
import { Route as LoopFitRouteImport } from './routes/loop-fit'
import { Route as MuscleRouteImport } from './routes/muscle'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SectionIdRouteImport } from './routes/section.$id'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixItRoute = FixItRouteImport.update({
  id: '/fix-it',
  path: '/fix-it',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopFitRoute = LoopFitRouteImport.update({
  id: '/loop-fit',
  path: '/loop-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const MuscleRoute = MuscleRouteImport.update({
  id: '/muscle',
  path: '/muscle',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIdRoute = SectionIdRouteImport.update({
  id: '/section/$id',
  path: '/section/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fix-it': typeof FixItRoute
  '/glossary': typeof GlossaryRoute
  '/kit': typeof KitRoute
  '/loop-fit': typeof LoopFitRoute
  '/muscle': typeof MuscleRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/sources': typeof SourcesRoute
  '/workflows': typeof WorkflowsRoute
  '/section/$id': typeof SectionIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fix-it': typeof FixItRoute
  '/glossary': typeof GlossaryRoute
  '/kit': typeof KitRoute
  '/loop-fit': typeof LoopFitRoute
  '/muscle': typeof MuscleRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/sources': typeof SourcesRoute
  '/workflows': typeof WorkflowsRoute
  '/section/$id': typeof SectionIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fix-it': typeof FixItRoute
  '/glossary': typeof GlossaryRoute
  '/kit': typeof KitRoute
  '/loop-fit': typeof LoopFitRoute
  '/muscle': typeof MuscleRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/sources': typeof SourcesRoute
  '/workflows': typeof WorkflowsRoute
  '/section/$id': typeof SectionIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fix-it'
    | '/glossary'
    | '/kit'
    | '/loop-fit'
    | '/muscle'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/shortcuts'
    | '/sources'
    | '/workflows'
    | '/section/$id'
    | '/workflow/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fix-it'
    | '/glossary'
    | '/kit'
    | '/loop-fit'
    | '/muscle'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/shortcuts'
    | '/sources'
    | '/workflows'
    | '/section/$id'
    | '/workflow/$id'
  id:
    | '__root__'
    | '/'
    | '/fix-it'
    | '/glossary'
    | '/kit'
    | '/loop-fit'
    | '/muscle'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/shortcuts'
    | '/sources'
    | '/workflows'
    | '/section/$id'
    | '/workflow/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixItRoute: typeof FixItRoute
  GlossaryRoute: typeof GlossaryRoute
  KitRoute: typeof KitRoute
  LoopFitRoute: typeof LoopFitRoute
  MuscleRoute: typeof MuscleRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShortcutsRoute: typeof ShortcutsRoute
  SourcesRoute: typeof SourcesRoute
  WorkflowsRoute: typeof WorkflowsRoute
  SectionIdRoute: typeof SectionIdRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-it': {
      id: '/fix-it'
      path: '/fix-it'
      fullPath: '/fix-it'
      preLoaderRoute: typeof FixItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop-fit': {
      id: '/loop-fit'
      path: '/loop-fit'
      fullPath: '/loop-fit'
      preLoaderRoute: typeof LoopFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscle': {
      id: '/muscle'
      path: '/muscle'
      fullPath: '/muscle'
      preLoaderRoute: typeof MuscleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$id': {
      id: '/section/$id'
      path: '/section/$id'
      fullPath: '/section/$id'
      preLoaderRoute: typeof SectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixItRoute: FixItRoute,
  GlossaryRoute: GlossaryRoute,
  KitRoute: KitRoute,
  LoopFitRoute: LoopFitRoute,
  MuscleRoute: MuscleRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShortcutsRoute: ShortcutsRoute,
  SourcesRoute: SourcesRoute,
  WorkflowsRoute: WorkflowsRoute,
  SectionIdRoute: SectionIdRoute,
  WorkflowIdRoute: WorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
